Add support for nested routers
wesleytodd/express-openapi pull request #56
Opened 2023-11-03 15:44 UTC by Megapixel99

Fixes #20 and adds a test.

2023-11-03 16:58 UTC, wesleytodd requested changes
I *think* this is good, but I would really like to make sure I understand all the regex operations before I approve.

2023-11-03 16:58 UTC, wesleytodd commented on lib/generate-doc.js
> +function processComplexMatch (thing, keys) {
I think we need some comments here. This is looking for the key and then replacing it with the key template syntax?  There are a bunch of replaces there I am not sure I am following. An approach I like to use is to pull all the regex's out and name them variable that explain what they match. Ideally outside of the function scope so they are recreated each call for no reason.

2023-11-03 17:41 UTC, wesleytodd commented on lib/generate-doc.js
> +function processComplexMatch (thing, keys) {
Yeah, that was my thinking (add it to code comments). I think I followed most of this but it takes a bit and comments and/or var names would go along way to making this maintainable longer term and for folks who might not be as deep into it as we are.

2023-11-03 18:34 UTC, wesleytodd commented on lib/generate-doc.js
> +function processComplexMatch (thing, keys) {
Mind adding one over the middle block just to cover all of them?

2023-11-03 19:18 UTC, Megapixel99 commented
I removed a few lines of code that were not doing anything and reformatted the code, it should be a little cleaner

2023-11-03 19:34 UTC, Megapixel99 commented
Streamlined the process with less code

2023-11-03 19:34 UTC, enov approved these changes
LGTM!

2023-11-06 16:11 UTC, wesleytodd approved these changes

2023-11-06 16:11 UTC, merged